### ISSUE TITLE
Is it possible to use it to debounce a worn-out mouse switches?

### ISSUE THREAD

**Issue by trappedinspacetime** [kermitfrog/inputmangler#1]
First of all congrats on your project, it looks promising. 

I wonder if I can use it to fix my faulty mouse. In Windows I use an Autohotkey script , which is very efficient to debounce my mouse. I post the algorithm here in case it gives an idea:

     LButton::  ;sets the left button as a hotkey and intercepts the functions of the left button switch events 
        If (A_TimeSincePriorHotkey < 150) ;A_TimeSincePriorHotkey is a built-in variable it counts the time between two clicks  
           Return ;if the elapsed time is less than 150ms then it`s a hyperclick and ignore the clicks
        Click Down ; if it gets decent events which lasts longer than 150ms, it simulates a click down event
        KeyWait, LButton ; waits for another left button press 
        Click Up ; finishes up a decent click
     Return

May your code can be used for that purpose?

Regards.
Kenn

**Comment by kermitfrog** [comment]
Thanks! :)

Debouncing isn't possible yet, but i was planning to implement tracking the state of keys/buttons anyway.
Once that's done, it should be easy to grant your wish - can't say when that will be though. I expect something between a few days and the end of January.

Just to make sure, i understand the Algorithm:
`KeyWait, LButton ;` waits for an press **or** release, which in this case should be a release, right?

**Comment by trappedinspacetime** [comment]
Thank you for responding. It can be any left button event, either a button up or button down.  
Once upon a time I studied Autohotkey scripts a bit. It's easy to use, you can try it, here is the download link: https://autohotkey.com/download/ahk-install.exe 
After you install it in Windows open notepad and try this :)

        RButton::

save it with blok_rclick.ahk extension and run it. It blocks your right button completely. To quit it: double click H icon in systray and exit  from menu item. You can remap any key  like 

      h::b

**Comment by trappedinspacetime** [comment]
by the way I forgot to mention `Click Up` sends `left click button up` event.

**Comment by kermitfrog** [comment]
Ok... the current version here should do it :)
There are some not yet documented changes in the conf format, but the following minimal config.xml should do the trick. just insert your mouses vendor and product values.

```
<?xml version="1.0" encoding="UTF-8"?>
<inputmanglerConf configVersion="2">
        <handlers>
                <device name="Mouse" vendor="" product="" id="M">
                        <signal key="BTN_LEFT" default="~D(BTN_LEFT, 150~)" />
                </device>
        </handlers>
</inputmanglerConf>
```


Can you test it and tell me if it works like you expected?

**Comment by trappedinspacetime** [comment]
Hi, thank you for quick fix. I am on Ubuntu 14.04.5 i386 platform. I did a debian compilation like `debuild -i -us -uc -b`, compilation passed successfully but when I try to install it, I get `inputdummy-dkms` dependency error.

**Comment by trappedinspacetime** [comment]
I'm sorry, it's my ignorance, I just noticed `inputdummy` directory in cloned repo, I just compiled the driver.

**Comment by trappedinspacetime** [comment]
By the way, when I attempted to compile **inputdummy** in its directory with `debuild -i -us -uc -b` my compiler fails

       Makefile:614: Cannot use CONFIG_CC_STACKPROTECTOR: -fstack-protector not supported by compiler

I don't know how to suppress it.

**Comment by kermitfrog** [comment]
Hm.. i don't remember ever having that problem... Have you tried the package? [https://tarbos.adhara.uberspace.de/pub/inputmangler/ubuntu/14.04/inputdummy-dkms_1.1_all.deb](url)

**Comment by trappedinspacetime** [comment]
Thank you again. I did 

     mkdir -p ~/.config/inputMangler/
and put the `config.xml` with the content you posted above. I ll test it tomorrow I hope, because I need to get back faulty mouse from my brother :)

**Comment by kermitfrog** [comment]
You're welcome :)

> mkdir -p ~/.config/inputMangler/

So far i assumed that you executed the setupHelper.sh script to set up your configuration directory.
If you haven't, you should do so, as inputmangler won't know what BTN_LEFT means without at least the keymap file in its config dir.

**Comment by trappedinspacetime** [comment]
Good afternoon,

I am sorry I am late at feedback. You know, on the way to a dentist your toothache relieves, the same happened to me, when I inserted my faulty old mouse it began to run smoothly, I thought your driver fixed the debouncing but I had not added mouse `verdor` and `product ids`, so as to make sure, I tried another died mouse but in that case hyperclicks occured again though I added mouse `verdor` and `product ids` into `config.xml`.  When I lost my hope, I noticed that the last plugged mouse was not in the list in `/etc/udev/rules.d/80-inputmangler.rules`, so I had to reinstall `inputmangler`. I need to test it a while in order to make sure if it works.

By the way, does your driver act on top of mouse driver? I don't know how it works.

**Comment by kermitfrog** [comment]
No problem - i know what you mean^^
I'll be gone from tomorrow until Wednesday, so take your time.

> By the way, does your driver act on top of mouse driver? I don't know how it works.

Not exactly on top..
The driver creates 4 virtual input devices (keyboard, mouse, tablet, joystick - in /dev/input/) and 4 device files (/dev/virtual_*) which inputmangler can write to.
Then inputmangler grabs your configured devices (so no output is sent to other applications), processes everything coming from them and sends new events to the driver via the appropriate /dev/virtual_ device.
These events are then generated by the kernel on the corresponding virtual input device and read by Xorg, your tty or whatever.
This approach is unfortunately a bit tricky to set up (i'm working on a first run wizard to help with this), but in my experience a lot more reliable than other applications like gizmod.
